version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - python
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
